### ISSUE TITLE
Pre-filled subject is cleared in contact form after sending email

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#104]
Hello HelpScout support,

I have found an issue that the pre-filled subject is cleared in contact form after sending email, then exit and open contact form again.
It also happens with SDK sample app.

Beacon SDK version: 2.1.0

**Actual outcome**
The pre-filled subject is empty after sending a message, exit and re-open contact form.

**Expected outcome**
The pre-filled subject should stay there every time opening the contact form.

Thanks,
Binh

**Comment by aliripe** [comment]
Hey @BinhTNT!

I have been able to reproduce this so I've created a ticket internally to track it. We will let you know once it's fixed.

Thank you for the feedback! 

Internal tracking card: [ANDSDK-484](https://helpscout.atlassian.net/browse/ANDSDK-484)

**Comment by jotaemepereira** [comment]
Hey @BinhTNT!

The pre-fill is intended for first-time contacts, to help the visitor fill out the form, on sub-sequent contact messages **within the same session** it will not display the pre-fill information. If you close the beacon and re-open it again, it will display the pre-fill information.

We are going to update the documentation to reflect the intended behavior because we realized it could be confusing.

Thanks for reaching out!
