### ISSUE TITLE
Add possibility to rate articles

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#107]
Beacon version: 2.1.0

I originally submitted this via email, but was told that GitHub was the right place for feature requests so I am reposting this here. 

The web beacon has the ability to rate articles, but this seems to be missing from the Mobile Beacon SDK:s. It isn't there on Android and I didn't see it on iOS. Without the ability to rate articles it is hard to know which articles that need improvement, so it would be great if this was added to the mobile beacons as well. I also know that you are striving for consistency between platforms and I think this feature would have great value. 

If there is a way to enable article ratings already for the mobile beacons, let me know and I'll close this.

**Comment by jotaemepereira** [comment]
Hey @sipersso! Article ratings are in the work pipeline of the mobile team. While I can't give you an ETA, I want to let you know we are already working on the feature so that you will have news from us soon.

I will leave this open, so we can ping you (and any other interested) once it is released.

Thanks!

**Comment by sipersso** [comment]
Cool! I think it will be a great addition.

**Comment by scottyab** [comment]
Hey @sipersso Article rating was included in release 2.1.2 #112
