### ISSUE TITLE
Beacon history tracks user activities from the latest message to before sending the new message

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#109]
Hello HelpScout support,

Regarding to Beacon history in conversation, I noticed that it is tracking user's activities counted from latest message to before the new message sent.
The case is below:
- User open article "Article A", then send a message --> Beacon history will be "Read Article A"
- User open article "Article B", then send new message --> Beacon history will be "Read Article B"
- User don't have any activities, then send new message --> Beacon history will not be seen

Only one email is used in this case. Could you please let me know if it is correct behavior?

Thanks,
Binh

**Comment by shaunmcilroy** [comment]
Hey @BinhTNT Beacon is designed to keep tabs on where a customer has been (where Beacon is enabled) prior to the message being submitted - can you upload a video of what you're describing as it sounds about right!

**Comment by BinhTNT** [comment]
Hi @shaunmcilroy Here is the video for what I described. I hope it will be more clear.
https://drive.google.com/file/d/195qcHWj5lwkYv7zmL7D01F1br1g1e8_4/view?usp=sharing

Thanks

**Comment by scottyab** [comment]
Hey @BinhTNT Sending a message or starting a chat will result in a Helpscout conversation and so the events (such as article view or search) up until that point are captured and added via Beacon SDK. You see them in the conversation as a note called "Beacon Activity".  We clear the tracking data afterwards.

From your description above, I believe your question is should the events be cleared when sending a new message? if so that yes, that is correct. You're seeing the expected behaviour. 

Let me know if that wasn't the question or if you have follow up issues. 

Thanks,
Scott
