### ISSUE TITLE
ProGuard optimisations

### ISSUE THREAD

**Issue by guan1** [helpscout/beacon-android-sdk-sample#125]
Hi,

After integrating your SDK we had to disable ProGuard optimisations (we had to use 
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' instead of proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' ), otherwise the BeaconActivity wouldn't be shown. Is this limitation on purpose?

* Beacon version: 
2.1.2

**Steps to reproduce**
1.  Use proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' 
            

**Actual outcome**
Beacon Activity isn't shown

**Expected outcome**
Beacon Activity should be shown

**Comment by codenameDuchess** [comment]
Hi @guan1,

Thanks for raising this issue and sorry for the trouble. [This issue](https://github.com/helpscout/beacon-android-sdk-sample/issues/96) has been reported in the past and we had been hopeful it would be resolved with our last update. So unfortunately you will need to stick to using proguard-rules.pro with the Beacon SDK for now.

However, we will look into this issue with the optimization rules in proguard-android-optimize.txt. We'll let you know if we're able to resolve it so that you can reenable ProGuard optimizations.

**Comment by codenameDuchess** [comment]
[Internal tracking link](https://helpscout.atlassian.net/browse/ANDSDK-571).

**Comment by guan1** [comment]
Hi,

any update on this?

Best regards,
Andre

**Comment by shaunmcilroy** [comment]
Hi @guan1 - we don't have any updates on this issue at this time, once we have an update we'll be sure to loop you in. For now I recommend following the advice my colleague mentioned above. 

For now you will need to stick to using proguard-android.txt with the Beacon SDK until we resolve this issue.

**Comment by aliripe** [comment]
Hey @guan1 and @Ditscheridou, we've pushed a fix for this as part of the new Beacon 2.3.2 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.
