### ISSUE TITLE
Is there a way to know when an article loaded completely?

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#139]
Hello,

I want to measure the time that is taken to load an article for tracking purpose. Is there any life cycle method or a way to trigger such an event?

Beacon SDK version: 2.2.2

Thanks,
Binh

**Comment by jotaemepereira** [comment]
👋  Hello @BinhTNT, we do not currently have any callback to know when an article was loaded, can I know a little bit more about the purpose of having this? Is it because you want to know if the articles you provide are too big?

I will leave this issue open so other users can put their thoughts in this.

Thanks!

**Comment by BinhTNT** [comment]
Hi @jotaemepereira 
"Is it because you want to know if the articles you provide are too big?" --> You are right, some articles that are too big and it take long time to load especially on Android.

**Comment by scottyab** [comment]
We have a [task](https://helpscout.atlassian.net/browse/MOBILE-213) already logged for this feature however it didn't include the time to load article (just the id) I've added this request to that for consideration.

**Comment by scottyab** [comment]
Hi, this is also another similar request that we should have merged into #81 flagging this with us.
