### ISSUE TITLE
SDK 2.3.3

### ISSUE THREAD

**Issue by chezhe** [helpscout/beacon-android-sdk-sample#172]
We are using Help scout Android SDK 2.3.3, but today we found it can't be installed. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ jcenter will shut down the service.
    
Because of some issues(upgrade our APP dependencies), we want to keep using 2.3.3 version. So could you move 2.3.3 SDK to marven centeral too?

**Comment by jotaemepereira** [comment]
👋🏼  Hey @chezhe, you can install the `.aar` manually from the `2.3.3` [release](https://github.com/helpscout/beacon-android-sdk-sample/releases/tag/2.3.3). 

We do not currently have plans to move older versions of the SDK to Maven Central, but we are interested in understanding your use case, can you explain a little bit more in detail why you cannot update to the latest Beacon version? Thanks!

**Comment by chezhe** [comment]
> 👋🏼 Hey @chezhe, you can install the `.aar` manually from the `2.3.3` [release](https://github.com/helpscout/beacon-android-sdk-sample/releases/tag/2.3.3).
> 
> We do not currently have plans to move older versions of the SDK to Maven Central, but we are interested in understanding your use case, can you explain a little bit more in detail why you cannot update to the latest Beacon version? Thanks!

Thanks for reply.
Cause we have a complex project, if upgrading beacon, maybe other dependencies need to be upgraded too. It occurs when I upgrade to 2.3.3, we have to upgrade sentry. We have other higher priority tasks to do.
And last time I try to upgrade to 3.0.1, I met some compile issue. I will try again later.

**Comment by scottyab** [comment]
Hi @chezhe just for some extra context the biggest change from 2.3.3 to 3.x.x was the changing of the repository location Bintray -> Maven Central and the artifact Id from `com.helpscout:beacon-ui:2.3.3` -> `com.helpscout:beacon:3.0.2` (we removed the `-ui`). 

There were minimal dependency changes that shouldn't affect your project 🤔 . For instance, we moved from Koin 2.2.1 to 3.0.1-beta-2 (due to 2.2.1 not being moved to Maven Central) and Kotlin 1.4.21 to 1.4.31. 

Hopefully, this helps! But if you're still seeing a compile issue please reopen this and let us know more details i.e Stacktrace and the output from `./gradlew :app:dependencies` Thanks
