### ISSUE TITLE
Input on the UI and UX

### ISSUE THREAD

**Issue by taaeng** [helpscout/beacon-android-sdk-sample#39]
- Status bar has low contrast. 
- Message icon is white on white background
- Back/navigate up button should have the correct Android design. (Use arrow_back, not keyboard_backspace)
- Close button in right corner is confusing for Android users. It should be a back-arrow on the left.
- Button has low contrast

<img width="360" alt="device-2019-01-21-222226" src="https://user-images.githubusercontent.com/1119881/51499925-6534be00-1dcc-11e9-9ea0-b0a61fcd8c87.png">
<img width="360" alt="device-2019-01-21-222525" src="https://user-images.githubusercontent.com/1119881/51499926-6534be00-1dcc-11e9-924c-436482d74484.png">

**Comment by scottyab** [comment]
Thanks for the feedback @taaeng and the helpful screenshots we'll discuss these points with our designer and get back to you.

**Comment by scottyab** [comment]
Hi @taaeng, 

We (the Android developers here at Help Scout) also raised this point about the Close/X button being confusing for Android users. But have agreed for now to keep it in to promote the fact users can exit out of the Beacon back into the app. I've logged your comment and we'll revisit this if/when more developers/users register the same concern. 

I've applied the following changes today that will be in the next SDK release.  

* Updated Send Button disabled colour to be lighter grey to increase contrast
* Fixed Fab buttons so their icon is tinted the same colour as toolbar text so when a beacon colour is very light i.e white, the icon is black.
* updated the Back arrow icon to use the correct Material design back rather than keyboard back
* Added subtle page background grey colour to match designs. This helps with seeing loading spinner and the "we're on it" circle/tick if beacon colour is white
* The Send a message screen was setting the primary colour instead of primary dark as the status bar colour. 

Thanks again for highlighting these UI issues.

**Comment by jotaemepereira** [comment]
@taaeng The changes that @scottyab mentioned are live on the `0.3.0` [version](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md). Thank you very much for your feedback!

**Comment by taaeng** [comment]
Nice. :-) 
Some minor input:
- Statusbar is still low in contrast
- The Send button could be more material. More left/right padding. And it looks like a contained button when disabled, and a text button when enabled.
https://material.io/design/components/buttons.html

Contained:
![mio-design_assets_1svn3mybheddwau1n2dro9ccdo6j-3e1g_contained-buttons-states](https://user-images.githubusercontent.com/1119881/52292927-06e40f80-2976-11e9-8a83-6312f1756e57.png)

Text button:
![mio-design_assets_14c0hqgvluf8kdmuij_av5puypmortu2u_text-buttons-states](https://user-images.githubusercontent.com/1119881/52292920-0481b580-2976-11e9-990a-48c655f1e12d.png)
