### ISSUE TITLE
Article in support agent answer opens in web browser instead of in beacon

### ISSUE THREAD

**Issue by xiaohule** [helpscout/beacon-android-sdk-sample#99]
Hello,
With the latest Android SDK 2.1.1 on my Motorola phone running android 9 I have noticed an unhappy behavior.

**Steps to reproduce**
1. As a support agent, reply to a user email by adding a Docs article link
2. As a user open helpscout beacon from your Android app, go ASK>PREVIOUS CONVERSATIONS>open the support agent answer>tap on the article link.

**Actual outcome**
The article opens in the smartphone web browser

**Expected outcome**
The article should open in the in-app beacon

**Comment by hs-gv** [comment]
Thanks for reaching out @xiaohule .  Your message has been passed on to our Android team and we'll get back to you soon.

**Comment by scottyab** [comment]
Hey @xiaohule I agree it would be ideal for article links in conversations to open within the SDK rather than web browser. I've logged internal issue ANDSDK-475 for this and we will update when we have more information. Thanks for raising this.

**Comment by scottyab** [comment]
Hey @xiaohule there was an error and we didn't update this issue to close it. The feature to open Docs article links from previous conversations in the Article screen rather than web browser was adding in [SDK 2.2.1](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md#version-221-2020-09-09). Thanks for this suggestion!
